Unbreak Block an ad wizard
CatBlock/catblock pull request #125
Opened 2017-01-19 11:38 UTC by tomasko126

Fixes #124 

@kpeckett Could you please take a look and review? This is a high-priority bug, which should be fixed asap. Thanks!

2017-02-23 11:30 UTC, itskdog requested changes
This patch doesn't work for me. I've tried it on this page and after I opened it from the popup, it let me click an element but then disappeared and left the blue highlight following the cursor everywhere until I reloaded the page.

2017-02-23 15:38 UTC, tomasko126 commented
@kpeckett Fixed! :)

2017-02-24 15:32 UTC, tomasko126 commented
@kpeckett I've fixed it in last commit. Please take a look and try it now.

2017-02-24 18:02 UTC, itskdog approved these changes

2017-02-24 20:32 UTC, merged