Update links
CatBlock/catblock pull request #138
Opened 2017-03-25 13:39 UTC by tomasko126

Update links inside of the extension to the new homepage URL

2017-03-30 14:50 UTC, itskdog requested changes

2017-03-30 14:50 UTC, kpeckett commented on options/index.html
> +                    <a id="supportlink" href="http://catblock.tenderapp.com/home" target="_blank"></a>
<support.getcatblock.com>

2017-05-20 19:39 UTC, tomasko126 commented
@kpeckett I have addressed your review, please review again.

2017-05-20 21:36 UTC, tomasko126 commented on options/index.html
> +                    <a id="supportlink" href="http://catblock.tenderapp.com/home" target="_blank"></a>
@kpeckett Fixed.

2017-07-21 13:10 UTC, itskdog approved these changes

2017-07-23 23:13 UTC, merged